import jsPDF from 'jspdf';

interface ReportData {
  className?: string;
  totalStudents: number;
  avgQuizScore: number;
  avgExpCompletion: number;
  avgTimeSpent: number;
  alertStudents: { name: string; avg: number; weakChapters: string[] }[];
  experimentCompletion: { name: string; completed: number }[];
  topStudents: { name: string; avgScore: number }[];
  interventionSummary?: {
    totalStudents: number;
    improvementRate: number;
    avgGain: number;
  };
}

export async function generateTeachingReport(data: ReportData): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = 20;

  const addText = (text: string, size: number, style: 'normal' | 'bold' = 'normal') => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    const lines = doc.splitTextToSize(text, contentW);
    doc.text(lines, margin, y);
    y += lines.length * (size * 0.45) + 2;
  };

  const addLine = () => {
    doc.setDrawColor(200);
    doc.line(margin, y, pageW - margin, y);
    y += 4;
  };

  // Title
  doc.setTextColor(30, 64, 175);
  addText('Teaching Quality Report', 22, 'bold');
  doc.setTextColor(100);
  addText(`Class: ${data.className || 'All Classes'}  |  Generated: ${new Date().toLocaleDateString('zh-CN')}`, 9);
  addLine();

  // Overview
  doc.setTextColor(30);
  addText('Overview', 14, 'bold');
  const overview = [
    `Total Students: ${data.totalStudents}`,
    `Average Quiz Score: ${data.avgQuizScore}%`,
    `Experiment Completion: ${data.avgExpCompletion}%`,
    `Average Study Time: ${Math.round(data.avgTimeSpent / 60)} min`,
  ];
  for (const item of overview) {
    addText(`  ${item}`, 10);
  }
  y += 3;

  // Experiment completion
  if (data.experimentCompletion.length > 0) {
    addText('Experiment Completion', 14, 'bold');
    for (const exp of data.experimentCompletion.slice(0, 10)) {
      const bar = '█'.repeat(Math.round(exp.completed / Math.max(data.totalStudents, 1) * 20));
      addText(`  ${exp.name}: ${bar} ${exp.completed}/${data.totalStudents}`, 9);
    }
    y += 3;
  }

  // Top students
  if (data.topStudents.length > 0) {
    addText('Top Students', 14, 'bold');
    for (const s of data.topStudents.slice(0, 5)) {
      addText(`  ${s.name} - ${s.avgScore}%`, 10);
    }
    y += 3;
  }

  // Alert students
  if (data.alertStudents.length > 0) {
    addText('Alert Students (Score < 60%)', 14, 'bold');
    for (const s of data.alertStudents.slice(0, 10)) {
      const weak = s.weakChapters.length > 0 ? ` (Weak: ${s.weakChapters.slice(0, 3).join(', ')})` : '';
      addText(`  ${s.name}: ${Math.round(s.avg)}%${weak}`, 9);
    }
    y += 3;
  }

  // Intervention effect
  if (data.interventionSummary && data.interventionSummary.totalStudents > 0) {
    addText('Intervention Effectiveness', 14, 'bold');
    addText(`  Students Intervened: ${data.interventionSummary.totalStudents}`, 10);
    addText(`  Improvement Rate: ${data.interventionSummary.improvementRate}%`, 10);
    addText(`  Average Score Gain: ${data.interventionSummary.avgGain > 0 ? '+' : ''}${data.interventionSummary.avgGain} points`, 10);
  }

  // Footer
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text('Generated by EduCog-Micro Platform', margin, pageH - 8);

  doc.save(`teaching-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
